name: postman-newman-acr-azureappservice

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NOME_IMAGEM: apicalculoimc
  NOME_WEBAPP: groffecalculoimc
  CAMINHO_TESTES: ./Tests

jobs:

  build-tests-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
      
    - name: Build de imagem
      run: docker build . --file Dockerfile --tag ${{ secrets.AZURECR_REGISTRY }}/${{ env.NOME_IMAGEM }}:latest
                
    - name: Login no Azure Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ secrets.AZURECR_REGISTRY }}
        username: ${{ secrets.AZURECR_USERNAME }}
        password: ${{ secrets.AZURECR_PASSWORD }}

    - name: Geração de tag com número do Build e Push no Azure Container Registry
      run: |
        docker tag ${{ secrets.AZURECR_REGISTRY }}/${{ env.NOME_IMAGEM }}:latest ${{ secrets.AZURECR_REGISTRY }}/${{ env.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker push --all-tags ${{ secrets.AZURECR_REGISTRY }}/${{ env.NOME_IMAGEM }}
